                                                                           
version: '3.8'

services:
  migration:
    build:
      context: ./migration
    container_name: migration_dev
    ports:
      - "9093:9093"

  web:
    build:
      context: ./web
    container_name: library_dev
    ports:
      - "9090:9090"
    networks:
      - prod_default

volumes:
  postgres_data_dev:
  rabbitmq_data_dev:

networks:
  prod_default:


